apps/dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^signin$', views.signin, name = 'signin'),
    url(r'^register$', views.register, name = 'register'),
    url(r'^dashboard$', views.dashboard, name = 'dashboard'),
    url(r'^users/create$', views.new, name = 'create'),
    url(r'^users/edit$', views.profile, name = 'profile'),
    url(r'^users/show/(?P<id>\d+)$', views.show, name = 'show'),
    url(r'^users/edit/(?P<id>\d+)$', views.edit, name = 'edit'),
    url(r'^logout$', views.logout, name = 'logout'),
    url(r'^destroy$', views.destroy, name = "destroy")
]

user_dashboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.dashboard.urls', namespace = 'dash'))
]

apps/dashboard/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.validators import validate_email
from django.core.exceptions import ValidationError

class UserManager(models.Manager):

    def validate(self, post):

        errors = {}

        fname = post['first_name']
        if not fname.isalpha():
            errors['fname_alpha'] = 'First name must be only alphabetical characters'
        if not len(fname) >= 2:
            errors['fname_len'] = 'First name must be 2 or more characters'

        lname = post['last_name']
        if not lname.isalpha():
            errors['lname_alpha'] = 'Last name must be only alphabetical characters'
        if not len(lname) >= 2:
            errors['lname_len'] = 'Last name must be 2 or more characters'

        password = post['password']
        if not password == post['confirm_password']:
            errors['pw_mismatch'] = 'Passwords must match'
        if not len(password) >= 8:
            errors['pw_len'] = 'Password must be 8 or more characters'

        try:
            validate_email(post['email'])
        except ValidationError:
            errors['email_format'] = 'Email must be a valid address'
        else:
            if not errors:
                if User.objects.filter(email = post['email']):
                    errors['email_unique'] = 'User already exists'


        return errors

class User(models.Model):
    ADMIN = 9
    NORMAL = 1
    LEVEL = (
        (ADMIN, 'Admin'),
        (NORMAL, 'Normal')
    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    level = models.IntegerField(choices=LEVEL, default=NORMAL)
    password = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()


class Post(models.Model):
    entry = models.TextField()
    user = models.ForeignKey(User, related_name='posts')
    comment = models.ForeignKey('self', related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

apps/dashboard/forms.py
from django.forms import ModelForm, forms, PasswordInput, CharField
from .models import User

class UserForm(ModelForm):

    confirm_password = CharField(widget=PasswordInput())

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password']
        widgets = {
            'password' : PasswordInput,
        }


    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

apps/dashboard/views.py
from django.shortcuts import render, HttpResponse, redirect
import bcrypt
from .forms import UserForm
from .models import User
from django.contrib import messages
from django.core.urlresolvers import reverse

def index(request):
    if 'user' in request.session:
        return redirect(reverse('dash:dashboard'))
    return render(request, 'dashboard/index.html')

def signin(request):
    if 'user' in request.session:
        return redirect(reverse('dash:dashboard'))

    if request.method == "GET":
        return render(request, 'dashboard/signin.html')
    else:
        email = request.POST.get('email')
        password = request.POST.get('pw') 
        
        user = User.objects.filter(email = email).first()
        
    if user:
        valid_pw = bcrypt.checkpw(password.encode(), user.password.encode())
        if valid_pw:
            request.session['user'] = { 'id' : user.id, 'admin' : User.ADMIN == user.level }
            return redirect(reverse('dash:dashboard'))
        else:
            messages.error(request, 'Invalid user/password')
            return redirect(reverse('dash:signin'))                            
    else:
        messages.error(request, 'User does not exist')
        return redirect(reverse('dash:signin'))                                
    
def register(request):
    if 'user' in request.session:
        return redirect(reverse('dash:dashboard'))

    if request.method == 'GET':
        return render(request, 'dashboard/register.html', { 'form' : UserForm() })
    else:        
        form = UserForm(request.POST)
        errors = User.objects.validate(request.POST)
        if errors:
            for tag, error in errors.iteritems():
                messages.error(request, error)
            return redirect(reverse('dash:register'))
        else:
            user = form.save(commit=False)
            user.password = bcrypt.hashpw(user.password.encode(), bcrypt.gensalt())
            if User.objects.count() == 0:
                user.level = User.ADMIN
            user.save()
            request.session['user'] = { 'id' : user.id, 'admin' : User.ADMIN == user.level }
            return redirect(reverse('dash:dashboard')) 
    
def dashboard(request):
    if not 'user' in request.session:
        return redirect(reverse('dash:signin'))
    return render(request, 'dashboard/dashboard.html', { 'users' : User.objects.all() })

    
def profile(request):
    if not 'user' in request.session:
        return redirect(reverse('dash:signin'))
    if request.method == 'GET':        
        user = User.objects.get(id=request.session.get('user')['id'])
        return render(request, 'dashboard/profile.html', { 'form' : UserForm(instance=user) })           
    else:
        form = UserForm(request.POST)
        errors = User.objects.validate(request.POST)
        if errors:
            for tag, error in errors.iteritems():
                messages.error(request, error)
            return redirect(reverse('dash:create'))
        else:
            user = form.save(commit=False)
            user.password = bcrypt.hashpw(user.password.encode(), bcrypt.gensalt())
            user.save()
            return redirect(reverse('dash:dashboard'))
                

    
def new(request):
    if not request.session['user']:
        return redirect(reverse('dash:dashboard')) 
    elif not request.session['user']['admin']:
        return redirect(reverse('dash:dashboard'))
    else:
        if request.method == 'GET':
            return render(request, 'dashboard/new.html', { 'form' : UserForm() })
        else:
            form = UserForm(request.POST)
            errors = User.objects.validate(request.POST)
            if errors:
                for tag, error in errors.iteritems():
                    messages.error(request, error)
                return redirect(reverse('dash:create'))
            else:
                user = form.save(commit=False)
                user.password = bcrypt.hashpw(user.password.encode(), bcrypt.gensalt())
                user.save()
                return redirect(reverse('dash:dashboard'))                        

    
def show(request, id):
    return HttpResponse('show {}'.format(id))
    
def edit(request, id):
    return HttpResponse('edit {}'.format(id))

def logout(request):
    request.session.clear()
    return redirect(reverse('dash:index'))   
    
def destroy(request):
    if not request.session['user']:
        return redirect(reverse('dash:dashboard')) 
    elif not request.session['user']['admin']:
        return redirect(reverse('dash:dashboard'))
    else:
        print request.POST.get('id')
        id = int(request.POST.get('id'))
        User.objects.get(id=id).delete()
        return redirect(reverse('dash:dashboard'))
        
           

apps/dashboard/templates/dashboard/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <title>{% block title%}{% endblock %}</title>
        <script type="text/javascript">
            $(document).ready(function() {
                {% block jquery %}
                {% endblock %}
            });
        </script>
    </head>
    <body>
        <nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
            <span class="navbar-brand">Test App</span>
            <div class="collapse navbar-collapse">   
                <ul class="navbar-nav">
                    {% if not request.session.user %}
                    <li class="nav-item">
                        <a class="nav-link {% block menu_home_class %}{% endblock %}" href="{% url 'dash:index' %}">Home</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% block menu_dash_class %}{% endblock %}"" href="{% url 'dash:dashboard' %}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block menu_profile_class %}{% endblock %}"" href="{% url 'dash:profile' %}">Profile</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            {% if request.session.user %}
                <a class="btn btn-outline-danger" href="{% url 'dash:logout' %}">Logout</a>
            {% else %}
                <a class="btn btn-outline-success" href="{% url 'dash:signin' %}">Login</a>
            {% endif %}
        </nav>        
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

apps/dashboard/templates/dashboard/dashboard.html
{% extends 'dashboard/base.html' %}

{% block jquery %}
$(':button').click(function(){
        if ($(this).attr('clear') == 'true') {
            id = $(this).attr('id');
            $('#id').val(id);
            $('#name').text('Are you sure you want to delete ' + $('#name' + id + ' a').text() + ' ?');
        }
    });

    $('#cancel').click(function(){
        $('#id').val('');
        $('#name').text('');        
    });

    $('#confirm').click(function(){
        $('#delete').submit();
    });
{% endblock %}

{% block title %}
    {% if request.session.user.admin %}
        Admin
    {% else %}
        User
    {% endif %}
        Dashboard                
{% endblock %}

{% block menu_dash_class %}
    active
{% endblock %}


{% block content %}
    {% if users %}
        <div class="row">
            <div class="col">
                <h1>
                {% if request.session.user.admin %}Manage{% else %}All{% endif %} Users
                </h1>
            </div>
            <div class="col">
                {% if request.session.user.admin %}
                <a href="{% url 'dash:create' %}" class="btn btn-primary float-right">Add New</a>
                {% endif %}
            </div>
        {% if request.session.user.admin %}
        {% endif %}
        </div>
        <table class="table table-striped table-bordered table-dark mt-3">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Created at</th>
                    {% if request.session.user.admin %}
                    <th>actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td id="name{{ user.id }}"><a href="{% url 'dash:show' id=user.id %}" class="text-warning">{{ user.first_name }} {{ user.last_name }}</a></td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.created_at }}</td>
                    {% if request.session.user.admin %}
                    <td>
                        <a href="{% url 'dash:edit' id=user.id %}" class="btn btn-primary">Edit</a>
                        {% if not request.session.user.id == user.id %}
                        <button class="btn btn-danger" clear="true" data-toggle="modal" data-target="#myModal" id="{{ user.id }}">&times;</button>
                        {% endif %}
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="modal fade" id="myModal">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">      
                    <div class="modal-header">
                        <h4 class="modal-title text-danger">Confirmation</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>        
                    <div class="modal-body">
                       <p id="name" class="text-info font-weight-bold"></p>
                       <form method="POST" id="delete" action="{% url 'dash:destroy' %}">
                            {% csrf_token %}
                            <input type="hidden" name="id" id="id">
                       </form>
                    </div>        
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" id="confirm">Delete</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>        
                </div>
            </div>
        </div>        
    {% endif %}     
{% endblock %}

apps/dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}

{% block title %}
    Home Page
{% endblock %}

{% block menu_home_class %}
    active
{% endblock %}    

{% block content %}
    <div class="jumbotron">
        <h1>Welcome to the test</h1>
        <p>We're going to build a cool application using a MVC framework! This application was built by Danny Waldman [&forall;&Delta;&forall;&Dagger;m&lambda;&Pi;gl&Xi;r]</p>
    </div>
    <div class="row">
        <div class="col">
            <h3>Manage Users</h3>
            <p>Using the application, you'll learn how to add, remove and edit users for the application<p>
        </div>
        <div class="col">
            <h3>Leave Messages</h3>
            <p>Users will be able to leave a message to another user using the application<p>
        </div>
        <div class="col">
            <h3>Edit user Information</h3>
            <p>Admins will be able to edit another user's information (email address, first name, last name, etc.)</p>
        </div>
    </div>
{% endblock %}

apps/dashboard/templates/dashboard/new.html
{% extends 'dashboard/base.html' %}

{% block content %}
    <div class="row mb-5">
        <div class="col-5">
            <ul class="list-group">
            {% for message in messages %}
                <li class="list-group-item {% if message.tags %}{% if message.tags == 'error' %}list-group-item-danger{% else %}list-group-success-success{% endif %}{% endif %}">{{ message }}</li>
            {% endfor%}
            </ul>
         </div>
    </div>   
    <div class="row">
        <div class="col">
            <a href="{% url 'dash:dashboard' %}" class="btn btn-primary float-right">Return to Dashboard</a>
        </div>
    </div> 
    <div class="row">
        <div class="col-5">
            <h1>Add new user</h1>
            <form action="{% url 'dash:create' %}" method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}
                    <button type="submit" class="btn btn-success float-right">Add User</button>
            </form>
        </div>
    </div>     
{% endblock %}

apps/dashboard/templates/dashboard/profile.html
{% extends 'dashboard/base.html' %}

{% block menu_profile_class %}
    active
{% endblock %}    

{% block content %}
    <div class="row mb-5">
        <div class="col-5">
            <ul class="list-group">
            {% for message in messages %}
                <li class="list-group-item {% if message.tags %}{% if message.tags == 'error' %}list-group-item-danger{% else %}list-group-success-success{% endif %}{% endif %}">{{ message }}</li>
            {% endfor%}
            </ul>
         </div>
    </div>   
    <div class="row">
        <div class="col-5">
            <h1>Add new user</h1>
            <form action="{% url 'dash:profile' %}" method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}
                    <button type="submit" class="btn btn-success float-right">Update</button>
            </form>
        </div>
    </div>     
{% endblock %}

apps/dashboard/templates/dashboard/register.html
{% extends 'dashboard/base.html' %}

{% block content %}
    <div class="row mb-5">
        <div class="col-5">
            <ul class="list-group">
            {% for message in messages %}
                <li class="list-group-item {% if message.tags %}{% if message.tags == 'error' %}list-group-item-danger{% else %}list-group-success-success{% endif %}{% endif %}">{{ message }}</li>
            {% endfor%}
            </ul>
         </div>
    </div>    
    <div class="row">
        <div class="col-5">
            <h1>Register</h1>
            <form action="{% url 'dash:register' %}" method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}
                    <button type="submit" class="btn btn-success float-right">Register</button>
            </form>
            <a href="{% url 'dash:signin' %}">Signin</a>
        </div>
    </div>     
{% endblock %}

apps/dashboard/templates/dashboard/signin.html
{% extends 'dashboard/base.html' %}

{% block title %}
    Signin
{% endblock %}


{% block content %}
    <div class="row mb-3">
        <div class="col-5">
            <ul class="list-group">
            {% for message in messages %}
                <li class="list-group-item {% if message.tags %}{% if message.tags == 'error' %}list-group-item-danger{% else %}list-group-success-success{% endif %}{% endif %}">{{ message }}</li>
            {% endfor%}
            </ul>
         </div>
    </div>  
    <div class="row">    
        <div class="col-5">
            <h1>Signin</h1>
            <form method="POST" action="{% url 'dash:signin' %}" class="mb-3">
                {% csrf_token %}
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="text" name="email" class="form-control">
                </div>          
                <div class="form-group">
                    <label for="pw">Password:</label>
                    <input type="password" name="pw" class="form-control">
                </div>      
                <input type="submit" value="Signin" class="btn btn-success float-right">
            </form>
            <a href="{% url 'dash:register' %}">Register for an account</a>
        </div>
    </div>
{% endblock %}